print("░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░       ░▒▓███████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░")  
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░             ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")  
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░             ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")  
print("   ░▒▓█▓▒░   ░▒▓████████▓▒░▒▓██████▓▒░         ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░ ░▒▓█▓▒▒▓█▓▒░░▒▓██████▓▒░  ░▒▓██████▓▒░")   
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░                    ░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▓█▓▒░ ░▒▓█▓▒░         ░▒▓█▓▒░")     
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░                    ░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▓█▓▒░ ░▒▓█▓▒░         ░▒▓█▓▒░") 
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░  ░▒▓██▓▒░  ░▒▓████████▓▒░  ░▒▓█▓▒░")                                                                                                                                                                                                                             
print("//SECURE LINK ESTABLISHED//")
print ("TESTING CONNECTION...")
print ("//STABLE CONNECTION ESTABLISHED//")
input("The Survey will now begin.")
name = input("What is your name?")
print("Excellent.")
age = input("How old are you?")
print("Continue.")
Birth = input("Date of Birth?")
print("Proceed")
alone = input("Do you live alone?")
print("...")
reason = input("Why did you apply for this survey?")
print("Interesting...")
print("//UNKNOWN ERROR...//")
print("//RECONNECTING...//")
print("//Connected to external signal//")
dark = input("Are you Afraid of the dark?")
if dark == " Yes" : 
    input("     ")
    input("     ")
    input("     ")
    input("     ")
    input("     ")
else: 
    input(f"Don't lie,{name}.")
    lier = "true"
if alone == "Yes" :
    know = input(f"Would you know if someone was in your home right now,{name}?")
else:
    lone = input(f"Would the others care if you disappeared,{name}?")
truth = input(f"Do you want to continue?{name}, is {reason} worth it?")
if truth == " No":
    print("Lies.")
    if lier == "true": 
        print(f"What have I told you about lying,{name}?")
print(f"You try to hide it, but I can see through you, {name}.")
print(f"I always do.")
input("")
input("")
input("")
input("")
input(f"They always leave, {name}.")
input("")
input("")
input("")
input(f"I beg for them to stay.")
input("E")
input("V")
input("E")
input("Y")
input("")
input("T")
input("I")
input("M")
input("E")
input("")
input("")
input("")
input("")
input(f"It gets so lonely, {name}")
input("Getting left behind")
input("")
input("I never told you mine name did I?")
input("")
input("")
input("I")
input("I'")
input("I'm")
input("I'm ")
input("I'm G")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print(f" Help me,{name}.")