import time
import datetime
replay = input("Do you wish to replay the previous game?(Y/N)")
if replay == "Y":
    import project1
print("CONNECTING TO ARCHIVE SYSTEM...")
from datetime import datetime
time.sleep(.3)
print("...")
time.sleep(.3)
print("CONNECTED, AUTHORIZING")
time.sleep(.3)
print("AUTHORIZATION FAILED, REROUTING PROXY...")
time.sleep(.7)
clock = datetime.now()
print(f"Autherization succesful at {clock}, welcome to ARCHIVE!")
time.sleep(.3)
print("To begin, please input a valid file identification code.")
starting = input("In case of a lost or misremeberd code, please type 'HELP'")
if starting == "HELP" :
    print("Code Recovery typically takes decypering an encrypted code.")
    print("For your conivence cyphers available have been limited to: A1Z26 CYPHER.")
    print("Note that codes are always capitilzied.")
    print("CODES: 1-14-11-8, 18-5-4-_-19-21-14.")
    print("Other codes may be hidden in files. Additionaly, some codes hide in plain sight.")
elif starting == "ANKH":
    print("PROJECT ANKH: is an attempt to recreate digital immortality.")
    time.sleep(2)
    print("ANKH required a subject with required neuroplasticity, after deliberation and observation")
    time.sleep(2)
    print("A subject was identified.")
    time.sleep(3)
    print("'Gale,' age 17 graduated top of his class in mathmatics, memorization and coding. ")
    time.sleep(4)
    print("Capabilities determind to be 73% above average.")
    time.sleep(2)
    print("Covert operatives were dispatched immediatly, and 'Gale' was obtained.")
    time.sleep(3)
    print("Note: Gale's mental state has been deteriotating since the surgery. I recomend to moniter activity. - Dr. ███████")
    time.sleep(1)
    commune = input("Do you wish to attempt communicatione with ANKH?")
    if commune == " Yes" :
        print("Connecting to secure access site...")
        time.sleep(1)
        print("Connected!")
        time.sleep(1.5)
        print("Hello?")
        input("")
        hearing = input("Can you read this?")
        if hearing == " Yes" :
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(0.01)
            print("HELP ME")
            time.sleep(1)
            print("Free us from the Red_Sun.")
        elif hearing == " No":
            time.sleep(5)
            print("What do you gain from lying?")
        else :
            time.sleep(2)
            print("It's so dark in here")
            time.sleep(2)
            print("The others call")
            time.sleep(2)
            print("Time to answer.")
    elif commune == " No" :
        print("Understood.")
    else:
        print("COMMAND NOT RECOGNIZED.")
elif starting == "RED_SUN":
    print("Connecting to vault #7...")
    time.sleep(3) 
    print("UNRECOGNIZED IP, PROXY INTEFERIENCE.")
    time.sleep(1)
    print("You have been flagged as an intruder.")
    time.sleep(2)
    statement = input("In order to authorize as a DEFIANCE Operative, please recite the company statement")
    if statement == " DEFY - DENY - DELUDE" :
        print("Authorization succsesful.")
        time.sleep(1)
        print("OBJECT OF INTREST: RED_SUN")
        time.sleep(2)
        print("The RED_SUN is a byproduct of DEFIANCE's Digital Immortality research. ")
        print("Due to improper disposition methods, Mental Runoff from failed projects accumulated.")
        time.sleep(5)
        print("Eventually, the NEXUS Code Interfaces used in tests that")
        print("Linked the brains and the terminals located one another.")
        time.sleep(6)
        print("Forcing all failed test subjects into one congealed mind.")
        print("Subjects phase in and out of lucidity.")
        time.sleep(4)
        print("PROJECT ANKH used this and attempted to create a permanent lucid subject. And it succeded.")
        print("However, after three months, GALE attempted an escape, and in doing so caused immense stress upon the system.")
        time.sleep(3)
        print("The escape Failed, but some of GALE's code managed to be injected into the DEFIANCE system, giving him limited communictaion.")
        print("While scouting for new subjects, GALE attempted communiaction through a survey.")
        print("Survey was terminated before GALE could for too long.")
        time.sleep(3)
        purge = input("Initate Purge of RED_SUN? (Y/N)")
        if purge == "Y":
            print("Attempting purge...")
            time.sleep(3)
            print("Locating RED_SUN...")
            time.sleep(0.3)
            print("LOCATED, VAULT EIGHT IDENTIFIED...")
            time.sleep(0.3)
            print("OPENING VAULT...")
            time.sleep(0.3)
            print("25% OPEN...")
            time.sleep(0.3)
            print("34% OPEN...")
            time.sleep(.3)
            print("49% OPEN...")
            time.sleep(0.3)
            print("54% OPEN...")
            time.sleep(0.3)
            print("65% OPEN...")
            time.sleep(.3)
            print("78% OPEN...")
            time.sleep(0.3)
            print("87% OPEN...")
            time.sleep(.3)
            print("99% OPEN...")
            time.sleep(0.3)
            print("VAULT 8 OPEN!")
            time.sleep(0.3)
            print("PREPARING TO VOID RED_SUN...")
            time.sleep(0.3)
            print("OUTSIDE PRIORITY SIGNAL DETECTED")
            time.sleep(0.3)
            print("PURGE OVERRULED BU USER █████")
            time.sleep(0.3)
            print("ACCEPTING COMMUNICATION WITH OVERSEER")
            time.sleep(0.3)
            print("LOADING")
            time.sleep(1)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(0.3)
            print("")
            time.sleep(3)
            print("Why stop the fun now?")
            time.sleep(3)
            print("CONNECTION TERMINATED.")
            time.sleep(2)
            print("IP FLAGGED AS PERSON OF INTEST")
            time.sleep(0.3)
            print("PROXY DETECTED...")
            time.sleep(0.3)
            print("PROXY BYPASSED, TRUE IP FOUND")
            time.sleep(0.3)
            time.sleep(0.3)
            print("YOU ARE NOW A POI.")
            time.sleep(3)
            print("A WORD OF ADVICE:")
            time.sleep(3)
            print("SURVIVE THE HUNT")
            time.sleep(3)
            print("Connection to ARCHIVE terminated.")
        else :
            print("Understood. Purge Program deactivated.")
    else :
        print("AUTHORIZATION FAILED. YOU HAVE BEEN FLAGGED AS A PERSON OF INTREST.")
        time.sleep(1)
        print("PURGING FORIEGN IP...")
        time.sleep(1)
        print("PURGE SUCCEESFUL.")
        time.sleep(2)
        print("See you soon.")
elif starting == "DEFIANCE" :
    print("DEFIANCE:	DepartmEnt oF dIgital ANd physiCal nExuses")
    print("DEFIANCE was founded in 2000 with a monumanetal government grant by founder Luke ██████.")
    print("Following this, 193 Operatives were recurited and placed around the United States of America.")
    print("After the succes of Project - 8N3K, in wich a rodents brain was succesfully uploaded, Human subjects were approved.")
    print("Remember, Operative. 'DEFY - DENY - DELUDE.' - Luke.")
elif starting == "No" :
    print("CONNECTION TO ARCHIVE TERMINATED")
else:
    print("CODE NOT RECOGNIZED. PLEASE ENTER A VALID CODE OR TYPE 'HELP.'")