print("░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░    ░▒▓███████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░")  
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░          ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")  
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░          ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")  
print("   ░▒▓█▓▒░   ░▒▓████████▓▒░▒▓██████▓▒░      ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░ ░▒▓█▓▒▒▓█▓▒░░▒▓██████▓▒░  ░▒▓██████▓▒░")   
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░                 ░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▓█▓▒░ ░▒▓█▓▒░         ░▒▓█▓▒░")     
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░                 ░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▓█▓▒░ ░▒▓█▓▒░         ░▒▓█▓▒░") 
print("   ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░   ░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░  ░▒▓██▓▒░  ░▒▓████████▓▒░  ░▒▓█▓▒░")                                                                                                                                                                                                                             
print("//SECURE LINK ESTABLISHED//")
print ("TESTING CONNECTION...")
print ("//STABLE CONNECTION ESTABLISHED//")
input("The Survey begin shortly. ")
print("There will be times you will have to scroll up or hit enter if there is no question.")
input("Additionaly, for best experience and interactivity, please add a space and capitalize your answers.")
print(" Yes and No have the most interactivty.")
input("The Survey Will Now Begin")
name = input("What is your name?")
print("Excellent.")
age = input("How old are you?")
print("Continue.")
Birth = input("Date of Birth?")
print("Proceed")
alone = input("Do you live alone?")
print("...")
reason = input("Why did you apply for this survey?")
print("Interesting...")
print("//UNKNOWN ERROR...//")
print("//RECONNECTING...//")
print("//Connected to external signal//")
lier = "true"
dark = input("Are you afraid of the dark?")
if dark == " Yes" : 
    input("     ")
    input("     ")
    input("     ")
    input("     ")
    input("     ")
else: 
    input(f"Don't lie,{name}.")
    lier = "false"
if alone == " Yes" :
    know = input(f"Would you know if someone was in your home right now,{name}?")
else:
    lone = input(f"Would the others care if you disappeared,{name}?")
truth = input(f"Do you want to continue?{name}, is {reason} worth it?")
if truth == " No":
    print("Lies.")
    if lier == "false": 
        print(f"What have I told you about lying,{name}?")
print(f"You try to hide it, but I can see through you, {name}.")
print(f"I always do.")
input("")
input("")
input("")
input("")
input(f"They always leave, {name}.")
input("")
input("")
input("")
input(f"I beg for them to stay.")
input("")
input("E")
input("V")
input("E")
input("Y")
input("")
input("T")
input("I")
input("M")
input("E")
input("")
input("")
input("")
input("")
input(f"It gets so lonely, {name}")
input("Getting left behind")
input("")
input("I never told you my name did I?")
input("")
input("")
input("I")
input("I'")
input("I'm")
input("I'm ")
input("I'm G")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("                       Do you see me")
print("                 Trapped beneath the twilight")
print("             Can you hear me")
print("         Tortured in the redlight")
print("     Would you help me")
print("    Stuck between the night")
print("     Do you feel them")
print("       Cause of my plight") 
print("         Speak of us")
print("            Those trapped")
print("                  as the Red Sun")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("                                             Please")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print(f" Help me,{name}.")
input("")
                                     
                                     
print(f"               ███████               Name of Subject:'{name}'")
print(f"             ███████████             ")
print(f"            ████████████             Subject Age:{age} ")
print(f"            ████████████             ")
print(f"            ████████████             Date of Birth:{Birth}")
print(f"            ████████████             ")
print(f"             ███████████             Reason for Experementation:{reason}")
print(f"              █████████              ")
print(f"              █████████              Person(s) living with:{alone}")
print(f"            █████████████            ")
print(f"        █████████████████████        Nyctophobia: True (sensitive) ")
print(f"     ███████████████████████████     ")
print(f"    █████████████████████████████    Truthfull: {lier}")
print(f"    █████████████████████████████    ")
print(f"   ███████████████████████████████   //Note: Program terminated duet to Project Ankh's (Subject G###) ")
print(f"   ███████████████████████████████   attempted communication//")
print("           PICTURE OF SUBJECT")                                    
                                     
                                     